<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Quantitative Bias Analysis for Epidemiologic Data • episensr</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/simplex/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Quantitative Bias Analysis for Epidemiologic Data">
<meta property="og:description" content="episensr">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">episensr</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.9.999</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/episensr.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/b_probabilistic.html">Probabilistic Sensitivity Analysis</a>
    </li>
    <li>
      <a href="../articles/c_multiple_bias.html">Multiple Bias Modeling</a>
    </li>
    <li>
      <a href="../articles/d_other_sens.html">Additional Sensitivity Analyses</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/dhaine/episensr/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Quantitative Bias Analysis for Epidemiologic Data</h1>
                        <h4 class="author">Denis Haine</h4>
            
            <h4 class="date">2020-10-16</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/dhaine/episensr/blob/master/vignettes/episensr.Rmd"><code>vignettes/episensr.Rmd</code></a></small>
      <div class="hidden name"><code>episensr.Rmd</code></div>

    </div>

    
    
<p>Quantitative bias analysis allows to estimate nonrandom errors in epidemiologic studies, assessing the magnitude and direction of biases, and quantifying their uncertainties. Every study has some random error due to its limited sample size, and is susceptible to systematic errors as well, from selection bias to the presence of (un)known confounders or information bias (measurement error, including misclassification). Bias analysis methods were compiled by Lash et al. in their book <a href="https://www.springer.com/us/book/9780387879604">“Applying Quantitative Bias Analysis to Epidemiologic Data”</a>. This package implements the various bias analyses from that book, which are also <a href="https://sites.google.com/site/biasanalysis/">available</a> (for some) as a spreadsheet or a SAS macro, as well as some additional approaches. This vignette provides some examples on how to use the package.</p>
<p>(<em>Note: A Shiny app is available for some functions, at <a href="https://dhaine.shinyapps.io/apisensr/" class="uri">https://dhaine.shinyapps.io/apisensr/</a>.</em>, using the R package <code>apisensr</code> which is based on <code>episensr</code>.)</p>
<p>Functions available in <code>episensr</code> are:</p>
<ul>
<li>
<code>selection</code>: Selection bias</li>
<li>
<code>mbias</code>: Selection bias caused by M bias</li>
<li>
<code>confounders</code>: Unmeasured or unknown confounders</li>
<li>
<code>confounders.poly</code>: Polytomous confounders</li>
<li>
<code>confounders.emm</code>: Unmeasured or unknown confounders in the presence of effect modification</li>
<li>
<code>confounders.limit</code>: Bounding the bias limits of unmeasured confounding</li>
<li>
<code>confounders.array</code>: Bias due to unmeasured confounders based on confounding imbalance among exposed and unexposed</li>
<li>
<code>confounders.ext</code>: Unmeasured confounders based on external measurement</li>
<li>
<code>confounders.evalue</code>: E-value due to unmeasured confounder</li>
<li>
<code>misclassification</code>: Disease or exposure misclassification</li>
<li>
<code>misclassification_cov</code>: Covariate misclassification</li>
<li>
<code>bootstrap</code>: Bootstrap resampling for selection and misclassification bias</li>
<li>
<code>multidimBias</code>: Multidimensional bias analysis</li>
<li>
<code>probsens.sel</code>: Probabilistic analysis for selection bias</li>
<li>
<code>probsens.conf</code>: Probabilistic analysis for unmeasured confounding</li>
<li>
<code>probsens</code>: Probabilistic analysis for misclassification</li>
<li>
<code>probsens.irr.conf</code>: Probabilistic analysis for unmeasured confounding of person-time data</li>
<li>
<code>probsens.irr</code>: Probabilistic analysis for exposure misclassification of person-time data</li>
<li>
<code>multiple bias</code>: Multiple bias modeling</li>
</ul>
<div id="selection-bias" class="section level2">
<h2 class="hasAnchor">
<a href="#selection-bias" class="anchor"></a>Selection Bias</h2>
<p>We will use a case-control study by <a href="http://www.ncbi.nlm.nih.gov/pubmed/16523014">Stang et al.</a> on the relation between mobile phone use and uveal melanoma. The observed odds ratio for the association between regular mobile phone use vs. no mobile phone use with uveal melanoma incidence is 0.71 [95% CI 0.51-0.97]. But there was a substantial difference in participation rates between cases and controls (94% vs 55%, respectively) and so selection bias could have an impact on the association estimate. The 2X2 table for this study is the following:</p>
<table class="table">
<thead><tr class="header">
<th align="right"></th>
<th align="center">Regular use</th>
<th align="center">No use</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">Cases</td>
<td align="center">136</td>
<td align="center">107</td>
</tr>
<tr class="even">
<td align="right">Controls</td>
<td align="center">297</td>
<td align="center">165</td>
</tr>
</tbody>
</table>
<p>We use the function <code>selection</code> as shown below.</p>
<div class="sourceCode" id="cb1"><pre class="downlit">
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">episensr</span><span class="op">)</span></pre></div>
<pre><code>## Loading required package: ggplot2</code></pre>
<div class="sourceCode" id="cb3"><pre class="downlit">
<span class="va">stang</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/selection.html">selection</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">136</span>, <span class="fl">107</span>, <span class="fl">297</span>, <span class="fl">165</span><span class="op">)</span>,
                          dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"UM+"</span>, <span class="st">"UM-"</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Mobile+"</span>, <span class="st">"Mobile-"</span><span class="op">)</span><span class="op">)</span>,
                          nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                   bias_parms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.94</span>, <span class="fl">.85</span>, <span class="fl">.64</span>, <span class="fl">.25</span><span class="op">)</span><span class="op">)</span>
<span class="va">stang</span></pre></div>
<pre><code>## --Observed data-- 
##          Outcome: UM+ 
##        Comparing: Mobile+ vs. Mobile- 
## 
##     Mobile+ Mobile-
## UM+     136     107
## UM-     297     165
## 
##                                        2.5%     97.5%
## Observed Relative Risk: 0.7984287 0.6518303 0.9779975
##    Observed Odds Ratio: 0.7061267 0.5143958 0.9693215
## ---
##                                                 
## Selection Bias Corrected Relative Risk: 1.483780
##    Selection Bias Corrected Odds Ratio: 1.634608</code></pre>
<p>The various <code>episensr</code> functions return an object which is a list containing the input and output variables. You can check it out with <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code>.</p>
<p>The 2X2 table is provided as a matrix and selection probabilities given with the argument <code>bias_parms</code>, a vector with the 4 probabilities (guided by the participation rates in cases and controls) in the following order: among cases exposed, among cases unexposed, among noncases exposed, and among noncases unexposed. The output shows the observed 2X2 table and the observed odds ratio (and relative risk), followed by the corrected ones.</p>
</div>
<div id="misclassification-bias" class="section level2">
<h2 class="hasAnchor">
<a href="#misclassification-bias" class="anchor"></a>Misclassification Bias</h2>
<p>Misclassification bias can be assessed with the function <code>misclassification</code>. Confidence intervals for corrected association due to exposure misclassification are also directly available, or the estimates can also be bootstrapped (see below). The confidence intervals from the variance of the corrected odds ratio estimator in the <code>misclassification</code> function are computed as in <a href="http://onlinelibrary.wiley.com/doi/10.1002/sim.4780070704/full#abstract">Greenland et al.</a> and <a href="http://www.sciencedirect.com/science/article/pii/S1047279706000688">Chu et al.</a>. Using the example in Chu et al. of a case-control study of cigarette smoking and invasive pneumococcal disease, the unadjusted odds ratio is 4.32, with a 95% confidence interval of 2.96 to 6.31. Let’s say the sensitivity of self-reported smoking is 94% and specificity is 97%, for both the case and control groups:</p>
<div class="sourceCode" id="cb5"><pre class="downlit">
<span class="fu"><a href="../reference/misclassification.html">misclassification</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">126</span>, <span class="fl">92</span>, <span class="fl">71</span>, <span class="fl">224</span><span class="op">)</span>,
                         dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Case"</span>, <span class="st">"Control"</span><span class="op">)</span>,
                                         <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Smoking +"</span>, <span class="st">"Smoking - "</span><span class="op">)</span><span class="op">)</span>,
                         nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                  type <span class="op">=</span> <span class="st">"exposure"</span>,
                  bias_parms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.94</span>, <span class="fl">0.94</span>, <span class="fl">0.97</span>, <span class="fl">0.97</span><span class="op">)</span><span class="op">)</span></pre></div>
<pre><code>## --Observed data-- 
##          Outcome: Case 
##        Comparing: Smoking + vs. Smoking -  
## 
##         Smoking + Smoking - 
## Case          126         92
## Control        71        224
## 
##                                      2.5%    97.5%
## Observed Relative Risk: 2.196866 1.796016 2.687181
##    Observed Odds Ratio: 4.320882 2.958402 6.310846
## ---
##                                                              2.5%    97.5%
## Misclassification Bias Corrected Relative Risk: 2.377254                  
##    Misclassification Bias Corrected Odds Ratio: 5.024508 3.282534 7.690912</code></pre>
<p>The corrected odds ratio is now 5.02, with a widened 95% confidence interval (3.28 to 7.69). Note the bias despite the large sensitivity and specificity.</p>
<p>You can even reproduce the contour plots in Chu et al. paper!</p>
<div class="sourceCode" id="cb7"><pre class="downlit">
<span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>Se <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.582</span>, <span class="fl">1</span>, <span class="fl">0.02</span><span class="op">)</span>,
                   Sp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.762</span>, <span class="fl">1</span>, <span class="fl">0.02</span><span class="op">)</span><span class="op">)</span>

<span class="va">dat</span><span class="op">$</span><span class="va">OR_c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">dat</span>, <span class="fl">1</span>,
                  <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="../reference/misclassification.html">misclassification</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">126</span>, <span class="fl">92</span>, <span class="fl">71</span>, <span class="fl">224</span><span class="op">)</span>,
                                                       nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                                                type <span class="op">=</span> <span class="st">"exposure"</span>,
                                                bias_parms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">x</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="va">x</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="va">x</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, <span class="va">x</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">$</span><span class="va">adj.measures</span><span class="op">[</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">]</span><span class="op">)</span>
<span class="va">dat</span><span class="op">$</span><span class="va">OR_c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">OR_c</span>, <span class="fl">2</span><span class="op">)</span>

<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tdhock/directlabels">directlabels</a></span><span class="op">)</span>
<span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dat</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Se</span>, y <span class="op">=</span> <span class="va">Sp</span>, z <span class="op">=</span> <span class="va">OR_c</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_contour.html">geom_contour</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="va">..level..</span><span class="op">)</span>, breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4.32</span>, <span class="fl">6.96</span>, <span class="fl">8.56</span>, <span class="fl">12.79</span>, <span class="fl">23.41</span>, <span class="fl">432.1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">"text"</span>, x <span class="op">=</span> <span class="fl">1</span>, y <span class="op">=</span> <span class="fl">1</span>, label <span class="op">=</span> <span class="st">"4.32"</span>, size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradient</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">OR_c</span><span class="op">)</span>, high <span class="op">=</span> <span class="st">'red'</span>, low <span class="op">=</span> <span class="st">'green'</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">1</span>, <span class="fl">.1</span><span class="op">)</span>, expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">1</span>, <span class="fl">.1</span><span class="op">)</span>, expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">1.025</span><span class="op">)</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">1.025</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_colour_gradient</a></span><span class="op">(</span>guide <span class="op">=</span> <span class="st">'none'</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Sensitivity"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Specificity"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Estimates of Corrected OR"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/directlabels/man/direct.label.html">direct.label</a></span><span class="op">(</span><span class="va">p1</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"far.from.others.borders"</span>, <span class="st">"calc.boxes"</span>, <span class="st">"enlarge.box"</span>, 
                      hjust <span class="op">=</span> <span class="fl">1</span>, vjust <span class="op">=</span> <span class="op">-</span><span class="fl">.5</span>, box.color <span class="op">=</span> <span class="cn">NA</span>, cex <span class="op">=</span> <span class="fl">.6</span>,
                      fill <span class="op">=</span> <span class="st">"transparent"</span>, <span class="st">"draw.rects"</span><span class="op">)</span><span class="op">)</span></pre></div>
<div class="figure">
<img src="episensr_files/figure-html/unnamed-chunk-1-1.png" alt="Contour plot of point estimates of corrected odds ratio (OR)" width="576"><p class="caption">
Contour plot of point estimates of corrected odds ratio (OR)
</p>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit">
<span class="va">dat</span><span class="op">$</span><span class="va">ORc_lci</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">dat</span>, <span class="fl">1</span>,
                     <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="../reference/misclassification.html">misclassification</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">126</span>, <span class="fl">92</span>, <span class="fl">71</span>, <span class="fl">224</span><span class="op">)</span>,
                                                          nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                                                   type <span class="op">=</span> <span class="st">"exposure"</span>,
                                                   bias_parms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">x</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="va">x</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="va">x</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, <span class="va">x</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">$</span><span class="va">adj.measures</span><span class="op">[</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">]</span><span class="op">)</span>
<span class="va">dat</span><span class="op">$</span><span class="va">ORc_lci</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">ORc_lci</span>, <span class="fl">2</span><span class="op">)</span>

<span class="va">p3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dat</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Se</span>, y <span class="op">=</span> <span class="va">Sp</span>, z <span class="op">=</span> <span class="va">ORc_lci</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_contour.html">geom_contour</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="va">..level..</span><span class="op">)</span>,
                 breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4.05</span>, <span class="fl">4.64</span>, <span class="fl">5.68</span>, <span class="fl">7.00</span>, <span class="fl">9.60</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">"text"</span>, x <span class="op">=</span> <span class="fl">1</span>, y <span class="op">=</span> <span class="fl">1</span>, label <span class="op">=</span> <span class="st">"2.96"</span>, size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradient</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">ORc_lci</span><span class="op">)</span>, high <span class="op">=</span> <span class="st">'red'</span>, low <span class="op">=</span> <span class="st">'green'</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">1</span>, <span class="fl">.1</span><span class="op">)</span>, expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">1</span>, <span class="fl">.1</span><span class="op">)</span>, expand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">1.025</span><span class="op">)</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">1.025</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_colour_gradient</a></span><span class="op">(</span>guide <span class="op">=</span> <span class="st">'none'</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Sensitivity"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Specificity"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"95% LCI of Corrected OR"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/directlabels/man/direct.label.html">direct.label</a></span><span class="op">(</span><span class="va">p3</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"far.from.others.borders"</span>, <span class="st">"calc.boxes"</span>, <span class="st">"enlarge.box"</span>, 
                           hjust <span class="op">=</span> <span class="fl">1</span>, vjust <span class="op">=</span> <span class="op">-</span><span class="fl">.5</span>, box.color <span class="op">=</span> <span class="cn">NA</span>, cex <span class="op">=</span> <span class="fl">.6</span>,
                           fill <span class="op">=</span> <span class="st">"transparent"</span>, <span class="st">"draw.rects"</span><span class="op">)</span><span class="op">)</span></pre></div>
<div class="figure">
<img src="episensr_files/figure-html/unnamed-chunk-2-1.png" alt="Contour plot of 95% lower confidence limit of corrected OR" width="576"><p class="caption">
Contour plot of 95% lower confidence limit of corrected OR
</p>
</div>
<p>Covariate misclassification is available via the function <code>misclassification.cov</code>. For example, the paper by <a href="http://www.bmj.com/content/330/7495/815">Berry et al.</a> looked if misclassification of the confounding variable <em>in vitro fertilization</em> (IVF), a confounder, resulted wrongly on an association between increase folic acid and having twins. IVF increases the risk of twins, and women undergoing IVF might be more likely to take folic acid supplements, i.e. IVF would be a confounder between vitamins and twins. Data on IVF were not available and a proxy for it was used, <em>period of involuntary childlessness</em>. However, it was a poor proxy for IVF, with a sensitivity of 60% and a specificity of 95%. These bias parameters were assumed to be nondifferential. Here’s the code with <code>episensr</code>:</p>
<div class="sourceCode" id="cb9"><pre class="downlit">
<span class="fu"><a href="../reference/misclassification_cov.html">misclassification.cov</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">array</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1319</span>, <span class="fl">38054</span>, <span class="fl">5641</span>, <span class="fl">405546</span>, <span class="fl">565</span>, <span class="fl">3583</span>,
                              <span class="fl">781</span>, <span class="fl">21958</span>, <span class="fl">754</span>, <span class="fl">34471</span>, <span class="fl">4860</span>, <span class="fl">383588</span><span class="op">)</span>,
                            dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Twins+"</span>, <span class="st">"Twins-"</span><span class="op">)</span>,
                                            <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Folic acid+"</span>, <span class="st">"Folic acid-"</span><span class="op">)</span>,
                                            <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Total"</span>, <span class="st">"IVF+"</span>, <span class="st">"IVF-"</span><span class="op">)</span><span class="op">)</span>,
                            dim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span>,
                      bias_parms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.6</span>, <span class="fl">.6</span>, <span class="fl">.95</span>, <span class="fl">.95</span><span class="op">)</span><span class="op">)</span></pre></div>
<pre><code>## --Observed data-- 
##          Outcome: Twins+ 
##        Comparing: Folic acid+ vs. Folic acid- 
## 
## , , Total
## 
##        Folic acid+ Folic acid-
## Twins+        1319        5641
## Twins-       38054      405546
## 
## , , IVF+
## 
##        Folic acid+ Folic acid-
## Twins+         565         781
## Twins-        3583       21958
## 
## , , IVF-
## 
##        Folic acid+ Folic acid-
## Twins+         754        4860
## Twins-       34471      383588
## 
## 
##                                      2.5%    97.5%
## Observed Relative Risk: 2.441910 2.301898 2.590437
##    Observed Odds Ratio: 2.491888 2.344757 2.648251
## ---
##                                                       Observed Corrected
##                       SMR RR adjusted for confounder: 2.261738  1.000235
##    RR due to confounding by misclassified confounder: 1.079661  2.441337
##           Mantel-Haenszel RR adjusted for confounder: 2.228816  1.000187
## MH RR due to confounding by misclassified confounder: 1.095608  2.441452
##                       SMR OR adjusted for confounder: 2.337898  1.000304
##    OR due to confounding by misclassified confounder: 1.065867  2.491131
##           Mantel-Haenszel OR adjusted for confounder: 2.290469  1.000215
## MH OR due to confounding by misclassified confounder: 1.087938  2.491351</code></pre>
<p>While the non-adjusted analysis showed that women taking folic acid were 2.44 times more likely to have twins, after correcting for the misclassification of IVF, risk ratio is now null (= 1.0).</p>
</div>
<div id="uncontrolled-confounders" class="section level2">
<h2 class="hasAnchor">
<a href="#uncontrolled-confounders" class="anchor"></a>Uncontrolled Confounders</h2>
<p>We will use data from a cross-sectional study by <a href="http://www.ncbi.nlm.nih.gov/pubmed/8879763">Tyndall et al.</a> on the association between male circumcision and the risk of acquiring HIV, which might be confounded by religion. The code to account for unmeasured or unknown confounders is the following, where the 2X2 table is given as a matrix. We choose a risk ratio implementation, provide a vector defining the risk ratio associating the confounder with the disease, and the prevalence of the confounder, religion, among the exposed and the unexposed.</p>
<div class="sourceCode" id="cb11"><pre class="downlit">
<span class="va">tyndall</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/confounders.html">confounders</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">105</span>, <span class="fl">85</span>, <span class="fl">527</span>, <span class="fl">93</span><span class="op">)</span>,
                              dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"HIV+"</span>, <span class="st">"HIV-"</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Circ+"</span>, <span class="st">"Circ-"</span><span class="op">)</span><span class="op">)</span>,
                              nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                       type <span class="op">=</span> <span class="st">"RR"</span>,
                       bias_parms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.63</span>, <span class="fl">.8</span>, <span class="fl">.05</span><span class="op">)</span><span class="op">)</span>
<span class="va">tyndall</span></pre></div>
<pre><code>## --Observed data-- 
##          Outcome: HIV+ 
##        Comparing: Circ+ vs. Circ- 
## 
##      Circ+ Circ-
## HIV+   105    85
## HIV-   527    93
## 
##                                             2.5%     97.5%
##         Crude Relative Risk: 0.3479151 0.2757026 0.4390417
## Relative Risk, Confounder +: 0.4850550                    
## Relative Risk, Confounder -: 0.4850550                    
## ---
##                                         Adjusted RR
## Standardized Morbidity Ratio: 0.4850550   0.7172695
##              Mantel-Haenszel: 0.4850550   0.7172695</code></pre>
<p>The output gives the crude 2X2 table, the crude relative risk and confounder specific measures of association between exposure and outcome, and the relationship adjusted for the unknown confounder, using a standardized morbidity ratio (SMR) or a Mantel-Haenszel (MH) estimate of the risk ratio.</p>
<p>Additional information are also available, like the 2X2 tables by levels of the confounder.</p>
<div class="sourceCode" id="cb13"><pre class="downlit">
<span class="co">## Confounder +</span>
<span class="va">tyndall</span><span class="op">$</span><span class="va">cfder.data</span></pre></div>
<pre><code>##          Circ+    Circ-
## HIV+  75.17045 2.727967
## HIV- 430.42955 6.172033</code></pre>
<div class="sourceCode" id="cb15"><pre class="downlit">
<span class="co">## Confounder -</span>
<span class="va">tyndall</span><span class="op">$</span><span class="va">nocfder.data</span></pre></div>
<pre><code>##         Circ+    Circ-
## HIV+ 29.82955 82.27203
## HIV- 96.57045 86.82797</code></pre>
</div>
<div id="bootstrapping" class="section level2">
<h2 class="hasAnchor">
<a href="#bootstrapping" class="anchor"></a>Bootstrapping</h2>
<p>Selection and misclassification bias models can be bootstrapped in order to get confidence interval on the adjusted association parameter. We can use the ICU dataset from Hosmer and Lemeshow <a href="http://ca.wiley.com/WileyCDA/WileyTitle/productCd-0470582472.html">Applied Logistic Regression</a> textbook as an example. The replicates that give negative cells in the adjusted 2X2 table are silently ignored and the number of effective bootstrap replicates is provided in the output. Ten thousands bootstrap samples are a good number for testing everything runs smoothly. But again, don’t be afraid of running more, like 100,000 bootstrap samples.</p>
<div class="sourceCode" id="cb17"><pre class="downlit">
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lbraglia/aplore3">aplore3</a></span><span class="op">)</span>  <span class="co"># to get ICU data</span>
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">icu</span><span class="op">)</span>

<span class="co">## First run the model</span>
<span class="va">misclass_eval</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/misclassification.html">misclassification</a></span><span class="op">(</span><span class="va">icu</span><span class="op">$</span><span class="va">sta</span>, <span class="va">icu</span><span class="op">$</span><span class="va">inf</span>,
                                   type <span class="op">=</span> <span class="st">"exposure"</span>,
                                   bias_parms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.75</span>, <span class="fl">.85</span>, <span class="fl">.9</span>, <span class="fl">.95</span><span class="op">)</span><span class="op">)</span>
<span class="va">misclass_eval</span></pre></div>
<pre><code>## --Observed data-- 
##          Outcome: Died 
##        Comparing: Yes vs. No 
## 
##        exposed
## case    Yes  No
##   Died   24  16
##   Lived  60 100
## 
##                                      2.5%    97.5%
## Observed Relative Risk: 2.071429 1.175157 3.651272
##    Observed Odds Ratio: 2.500000 1.230418 5.079573
## ---
##                                                                2.5%     97.5%
## Misclassification Bias Corrected Relative Risk:  3.627845                    
##    Misclassification Bias Corrected Odds Ratio:  4.871795  1.235506 19.210258</code></pre>
<div class="sourceCode" id="cb19"><pre class="downlit">
<span class="co">## Then bootstrap it</span>
<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>
<span class="va">misclass_boot</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/boot.bias.html">boot.bias</a></span><span class="op">(</span><span class="va">misclass_eval</span>, R <span class="op">=</span> <span class="fl">10000</span><span class="op">)</span>
<span class="va">misclass_boot</span></pre></div>
<pre><code>## 95 % confidence interval of the bias adjusted measures: 
##    RR: 0.9595117 11.96789 
##    OR: 1.075386 19.44271 
## ---
##  Based on 9562 bootstrap replicates</code></pre>
<p>Bootstrap replicates can also be plotted, with the confidence interval shown as dotted lines.</p>
<div class="sourceCode" id="cb21"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">misclass_boot</span>, <span class="st">"rr"</span><span class="op">)</span></pre></div>
<div class="figure">
<img src="episensr_files/figure-html/boot_fig-1.png" alt="Bootstrap replicates and confidence interval." width="700"><p class="caption">
Bootstrap replicates and confidence interval.
</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Denis Haine.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
