<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>1. Probabilistic Sensitivity Analysis • episensr</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/simplex/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="1. Probabilistic Sensitivity Analysis">
<meta property="og:description" content="episensr">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">episensr</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.9.6</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/episensr.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/multiple_bias.html">2. Multiple Bias Modeling</a>
    </li>
    <li>
      <a href="../articles/other_sens.html">3. Additional Sensitivity Analyses</a>
    </li>
    <li>
      <a href="../articles/probabilistic.html">1. Probabilistic Sensitivity Analysis</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/dhaine/episensr/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>1. Probabilistic Sensitivity Analysis</h1>
                        <h4 class="author">Denis Haine</h4>
            
            <h4 class="date">2020-10-08</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/dhaine/episensr/blob/master/vignettes/probabilistic.Rmd"><code>vignettes/probabilistic.Rmd</code></a></small>
      <div class="hidden name"><code>probabilistic.Rmd</code></div>

    </div>

    
    
<p>Bias parameters are not always known. A probabilistic sensitivity analysis allows to specify a probability distribution for the bias parameters and then, through Monte Carlo sampling, to generate a frequency distribution of the corrected estimates of effect. <code>episensr</code> has a set of <code>probsens</code> functions for this:</p>
<ul>
<li>
<code>probsens.sel</code>: Probabilistic analysis for selection bias</li>
<li>
<code>probsens.conf</code>: Probabilistic analysis for unmeasured confounding</li>
<li>
<code>probsens</code>: Probabilistic analysis for misclassification</li>
<li>
<code>probsens.irr.conf</code>: Probabilistic analysis for unmeasured confounding of person-time data</li>
<li>
<code>probsens.irr</code>: Probabilistic analysis for exposure misclassification of person-time data</li>
</ul>
<p>The available distributions for the various bias parameters throughout these functions are:</p>
<ul>
<li>Constant,</li>
<li>Uniform,</li>
<li>Triangular,</li>
<li>Trapezoidal,</li>
<li>Logit-logistic,</li>
<li>Logit-normal, and</li>
<li>Beta.</li>
</ul>
<div id="probabilistic-sensitivity-analysis-for-exposure-misclassification" class="section level2">
<h2 class="hasAnchor">
<a href="#probabilistic-sensitivity-analysis-for-exposure-misclassification" class="anchor"></a>Probabilistic Sensitivity Analysis for Exposure Misclassification</h2>
<p>We use a study on the effect of smoking during pregnancy on breast cancer risk by <a href="http://www.ncbi.nlm.nih.gov/pubmed/12946045">Fink &amp; Lash</a>, where we assume nondifferential misclassification of the exposure, smoking, with probability density functions for sensitivities (Se) and specificities (Sp) among cases and noncases equal to uniform distributions with a minimum of 0.7 and a maximum of 0.95 for sensitivities (0.9 and 0.99 respectively for specificities). We choose to correct for exposure misclassification with the argument <code>type = exposure</code>. We ask for 50000 replications (default is 1000). Don’t be shy with the number of iterations, episensr is fast.</p>
<p>The Se and Sp for cases (<code>seca</code>, <code>spca</code>) are given as a list with its first element referring to the type of distribution (choice between constant, uniform, triangular, trapezoidal, logit-logistic, and logit-normal) and the second element giving the distribution parameters (min and max for uniform distribution). By avoiding to provide information on the noncases (<code>seexp</code>, <code>spexp</code>), we are referring to a nondifferential misclassification.</p>
<div class="sourceCode" id="cb1"><pre class="downlit">
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">episensr</span><span class="op">)</span></pre></div>
<pre><code>## Loading required package: ggplot2</code></pre>
<div class="sourceCode" id="cb3"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>
<span class="va">smoke.nd</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/probsens.html">probsens</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">215</span>, <span class="fl">1449</span>, <span class="fl">668</span>, <span class="fl">4296</span><span class="op">)</span>,
                            dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"BC+"</span>, <span class="st">"BC-"</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Smoke+"</span>, <span class="st">"Smoke-"</span><span class="op">)</span><span class="op">)</span>,
                            nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                     type <span class="op">=</span> <span class="st">"exposure"</span>,
                     reps <span class="op">=</span> <span class="fl">50000</span>,
                     seca.parms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"uniform"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.7</span>, <span class="fl">.95</span><span class="op">)</span><span class="op">)</span>,
                     spca.parms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"uniform"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.9</span>, <span class="fl">.99</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="va">smoke.nd</span></pre></div>
<pre><code>## --Observed data-- 
##          Outcome: BC+ 
##        Comparing: Smoke+ vs. Smoke- 
## 
##     Smoke+ Smoke-
## BC+    215   1449
## BC-    668   4296
## 
##                                         2.5%     97.5%
##  Observed Relative Risk: 0.9653825 0.8523766 1.0933704
##     Observed Odds Ratio: 0.9542406 0.8092461 1.1252141
## ---
##                                                  Median 2.5th percentile
##            Relative Risk -- systematic error: 0.9431650        0.8817325
##               Odds Ratio -- systematic error: 0.9253996        0.8478414
## Relative Risk -- systematic and random error: 0.9359816        0.8175818
##    Odds Ratio -- systematic and random error: 0.9162763        0.7664183
##                                               97.5th percentile
##            Relative Risk -- systematic error:         0.9612154
##               Odds Ratio -- systematic error:         0.9487841
## Relative Risk -- systematic and random error:         1.0690389
##    Odds Ratio -- systematic and random error:         1.0923026</code></pre>
<p>The output gives the 2X2 table, the observed measures of association, and the corrected measures of association.</p>
<p>We saved the <code>probsens</code> analysis in a new object <code>smoke.nd</code>. We can see its elements with the function <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code>:</p>
<div class="sourceCode" id="cb5"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">smoke.nd</span><span class="op">)</span></pre></div>
<pre><code>## List of 8
##  $ obs.data    : num [1:2, 1:2] 215 668 1449 4296
##   ..- attr(*, "dimnames")=List of 2
##   .. ..$ : chr [1:2] "BC+" "BC-"
##   .. ..$ : chr [1:2] "Smoke+" "Smoke-"
##  $ obs.measures: num [1:2, 1:3] 0.965 0.954 0.852 0.809 1.093 ...
##   ..- attr(*, "dimnames")=List of 2
##   .. ..$ : chr [1:2] " Observed Relative Risk:" "    Observed Odds Ratio:"
##   .. ..$ : chr [1:3] " " "2.5%" "97.5%"
##  $ adj.measures: num [1:4, 1:3] 0.943 0.925 0.936 0.916 0.882 ...
##   ..- attr(*, "dimnames")=List of 2
##   .. ..$ : chr [1:4] "           Relative Risk -- systematic error:" "              Odds Ratio -- systematic error:" "Relative Risk -- systematic and random error:" "   Odds Ratio -- systematic and random error:"
##   .. ..$ : chr [1:3] "Median" "2.5th percentile" "97.5th percentile"
##  $ sim.df      :'data.frame':    50000 obs. of  12 variables:
##   ..$ seca   : num [1:50000] 0.772 0.897 0.802 0.921 0.935 ...
##   ..$ seexp  : num [1:50000] 0.772 0.897 0.802 0.921 0.935 ...
##   ..$ spca   : num [1:50000] 0.919 0.94 0.912 0.943 0.965 ...
##   ..$ spexp  : num [1:50000] 0.919 0.94 0.912 0.943 0.965 ...
##   ..$ A1     : num [1:50000] 117 137 95 139 174 ...
##   ..$ B1     : num [1:50000] 1547 1527 1569 1525 1490 ...
##   ..$ C1     : num [1:50000] 386 442 321 446 548 ...
##   ..$ D1     : num [1:50000] 4578 4522 4643 4518 4416 ...
##   ..$ corr.RR: num [1:50000] 0.918 0.94 0.905 0.943 0.954 ...
##   ..$ corr.OR: num [1:50000] 0.893 0.922 0.877 0.925 0.94 ...
##   ..$ tot.RR : num [1:50000] 0.903 1.067 0.854 1.056 0.999 ...
##   ..$ tot.OR : num [1:50000] 0.873 1.09 0.812 1.075 0.999 ...
##  $ reps        : num 50000
##  $ fun         : chr "probsens"
##  $ warnings    : NULL
##  $ message     : NULL
##  - attr(*, "class")= chr [1:3] "episensr" "episensr.probsens" "list"</code></pre>
<p><code>smoke.nd</code> is a list of 8 elements where different information on the analysis done are saved. We have <code>smoke.nd$obs.data</code> where we have the observed 2X2 table, <code>smoke.nd$obs.measures</code> (the observed measures of association), <code>smoke.nd$adj.measures</code> (the adjusted measures of association), and <code>smoke.nd$sim.df</code>, a data frame with the simulated variables from each replication, like the Se and Sp, the 4 cells of the adjusted 2X2 table, and the adjusted measures. <code>episensr</code> offers some plot functions to allow plotting directly these saved infromation, for example the Se prior distribution:</p>
<div class="sourceCode" id="cb7"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">smoke.nd</span>, <span class="st">"seca"</span><span class="op">)</span></pre></div>
<div class="figure">
<img src="probabilistic_files/figure-html/plot-1.png" alt="Sensibility prior distribution." width="576"><p class="caption">
Sensibility prior distribution.
</p>
</div>
<p>There are combinations of Se, Sp, and disease (or exposure) prevalence that can produce negative cells in the corrected 2-by-2 table. For outcome misclassification, this happen when the frequency of observed exposed cases is less than the total number of diseased individuals multiplied by the false-positive proportion. Negative cell counts occur when the false-positive proportion is greater than the proportion of cases that are exposed. When providing values for Se and Sp that are more or less like random classification (i.e. Se ~50% and Sp ~50%), you can obtain negative cell values.</p>
<p>Note that a message is provided if the chosen distribution(s) lead to negative cell values, with the number of iterations affected. By default, these iterations are deleted from the simulation. However, user can keep these iterations which will be set to zero by setting <code>discard</code> to <code>FALSE</code>. It is recommended to shift distributions upwards if more than 10% of the iterations are deleted (<a href="https://doi.org/10.1093/ije/dyi184">Fox et al., 2005</a>).</p>
</div>
<div id="probabilistic-sensitivity-analysis-for-uncontrolled-confounding" class="section level2">
<h2 class="hasAnchor">
<a href="#probabilistic-sensitivity-analysis-for-uncontrolled-confounding" class="anchor"></a>Probabilistic Sensitivity Analysis for Uncontrolled Confounding</h2>
<p>Let’s illustrate this function with this example from <a href="https://shop.lww.com/Modern-Epidemiology/p/9781451190052">Modern Epidemiology by Rothman, Greenland &amp; Lash</a>, where the association between occupational resins exposure and lung cancer mortality is studied, together with the presence of an unmeasured potential confounder, smoking (<a href="https://www.ncbi.nlm.nih.gov/pubmed/7927843">Greenland et al., 1994</a>).</p>
<table class="table">
<thead><tr class="header">
<th align="right"></th>
<th align="center">Resins exposed</th>
<th align="center">Resins unexposed</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">Cases</td>
<td align="center">45</td>
<td align="center">94</td>
</tr>
<tr class="even">
<td align="right">Controls</td>
<td align="center">257</td>
<td align="center">945</td>
</tr>
</tbody>
</table>
<p>After adjustment for age and year at death, Greenland et al. found an OR of 1.77 (95% CI from 1.18 to 2.64). Is smoking, for which they had no data about, had an effect on this association? How large the association between resins and smoking had to be to remove the association between resins and lung cancer association after adjustment for smoking? For this, you have to know 3 bias parameters: the association between smoking and lung cancer, the prevalence of smoking among those unexposed to resins, and the prevalence of smoking in those exposed to resins.</p>
<p>Prior probability distributions are given to each bias parameters. Prevalences of smoking in those exposed to resins, and of smoking in those unexposed to resins receive prior distributions that are uniform between 0.40 and 0.70. Prior distribution for the odds ratio associating smoking with lung cancer mortality is log-normal with 95% limits of 5 and 15. The mean of this distribution is [ln(15) + ln(5)] / 2 = 2.159, and its standard deviation is [ln(15) - ln(5)] / 3.92 = 0.28. It looks like this:</p>
<div class="sourceCode" id="cb8"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>
<span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Lognormal.html">rlnorm</a></span><span class="op">(</span><span class="fl">10000</span>, meanlog <span class="op">=</span> <span class="fl">2.159</span>, sdlog <span class="op">=</span> <span class="fl">0.28</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">x</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.975</span><span class="op">)</span><span class="op">)</span></pre></div>
<pre><code>##      2.5%     97.5% 
##  4.979672 14.959055</code></pre>
<div class="sourceCode" id="cb10"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/density.html">density</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span></pre></div>
<div class="figure">
<img src="probabilistic_files/figure-html/unnamed-chunk-1-1.png" alt="Log-normal distribution with meanlog = 2.159 and sdlog = 0.28." width="576"><p class="caption">
Log-normal distribution with meanlog = 2.159 and sdlog = 0.28.
</p>
</div>
<p>Now, let’s run <code>probsens.conf</code> with 50,000 iterations:</p>
<div class="sourceCode" id="cb11"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>
<span class="va">greenland</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/probsens.conf.html">probsens.conf</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">45</span>, <span class="fl">94</span>, <span class="fl">257</span>, <span class="fl">945</span><span class="op">)</span>,
                                  dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Cases+"</span>, <span class="st">"Cases-"</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Res+"</span>, <span class="st">"Res-"</span><span class="op">)</span><span class="op">)</span>,
                                  nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
                           reps <span class="op">=</span> <span class="fl">50000</span>,
                           prev.exp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"uniform"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.4</span>, <span class="fl">.7</span><span class="op">)</span><span class="op">)</span>,
                           prev.nexp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"uniform"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.4</span>, <span class="fl">.7</span><span class="op">)</span><span class="op">)</span>,
                           risk <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"log-normal"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2.159</span>, <span class="fl">.28</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="va">greenland</span></pre></div>
<pre><code>## --Observed data-- 
##          Outcome: Cases+ 
##        Comparing: Res+ vs. Res- 
## 
##        Res+ Res-
## Cases+   45   94
## Cases-  257  945
## 
##                                      2.5%    97.5%
## Observed Relative Risk: 1.646999 1.182429 2.294094
##    Observed Odds Ratio: 1.760286 1.202457 2.576898
## ---
##                                            Median 2.5th percentile
##            RR (SMR) -- systematic error: 1.648388         1.166250
## RR (SMR) -- systematic and random error: 1.645768         1.018201
##            OR (SMR) -- systematic error: 1.841387         1.209338
## OR (SMR) -- systematic and random error: 1.841158         1.041488
##                                          97.5th percentile
##            RR (SMR) -- systematic error:          2.325654
## RR (SMR) -- systematic and random error:          2.670214
##            OR (SMR) -- systematic error:          2.822182
## OR (SMR) -- systematic and random error:          3.278307</code></pre>
<p>The median adjusted OR is 1.84 [1.21,2.82]. The ratio of the two 95% CI bounds is 2.82/1.21 = 2.33. The ratio from the conventional 95% confidence limits was 2.57/1.20 = 2.14. These 2 ratios are pretty close, and therefore our uncertainty about confounding is similar to our uncertainty about random error.</p>
<p>You can plot the bias-adjusted OR including both systematic and random error:</p>
<div class="sourceCode" id="cb13"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">greenland</span>, <span class="st">"or_tot"</span><span class="op">)</span></pre></div>
<div class="figure">
<img src="probabilistic_files/figure-html/probsens_conf_plot-1.png" alt="Distribution of the 50,000 confounder-adjusted odds ratios." width="576"><p class="caption">
Distribution of the 50,000 confounder-adjusted odds ratios.
</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Denis Haine.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
