# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpprbinom <- function(n, size, prob) {
    .Call(`_episensr_cpprbinom`, n, size, prob)
}

calc_RRexpo <- function(iter, obs_mat, draws) {
    .Call(`_episensr_calc_RRexpo`, iter, obs_mat, draws)
}

