# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpprbinom <- function(n, size, prob) {
    .Call(`_episensr_cpprbinom`, n, size, prob)
}

define_estar <- function(iter, obs_mat, draws) {
    .Call(`_episensr_define_estar`, iter, obs_mat, draws)
}

expo_adjOR <- function(iter, obs_mat, draws, display_progress = TRUE) {
    .Call(`_episensr_expo_adjOR`, iter, obs_mat, draws, display_progress)
}

expo_adjRR <- function(iter, obs_mat, draws, display_progress = TRUE) {
    .Call(`_episensr_expo_adjRR`, iter, obs_mat, draws, display_progress)
}

